# Generated by Django 5.0.6 on 2024-06-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_user_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles_pics/', verbose_name='Profile picture'),
        ),
    ]
