# Generated by Django 5.0.6 on 2024-06-27 15:16

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True, validators=[profiles.models.validate_username], verbose_name='Username'),
        ),
    ]
