# Generated by Django 5.0.6 on 2024-06-27 17:03

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(validators=[profiles.models.validate_birthdate], verbose_name='Date of birth'),
        ),
    ]
