# Generated by Django 5.0.6 on 2024-07-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_user_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_pics/Default_pfp.svg', null=True, upload_to='profiles_pics/', verbose_name='Profile picture'),
        ),
    ]
