# Generated by Django 5.0.6 on 2024-07-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_alter_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='profile_pics/Default_pfp.svg', upload_to='profiles_pics/', verbose_name='Profile picture'),
        ),
    ]
