# Generated by Django 5.0.6 on 2024-07-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='profile_pics/Default_pfp.svg.png', upload_to='profiles_pics/', verbose_name='Profile picture'),
        ),
    ]
