# Generated by Django 5.0.6 on 2024-07-22 20:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0015_alter_user_profile_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("friends", "friends"),
                            ("pending", "pending"),
                            ("non-friends", "non-friends"),
                        ],
                        default="pending",
                        max_length=255,
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="relationships", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
