# Generated by Django 5.0.6 on 2024-07-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('friends', 'friends'), ('pending', 'pending'), ('non-friends', 'non-friends')], default='non-friends', max_length=255),
        ),
    ]
