# Generated by Django 5.0.6 on 2024-07-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_alter_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('friends', 'friends'), ('pending', 'pending')], default='pending', max_length=255),
        ),
    ]
