# Generated by Django 5.0.6 on 2024-07-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='status',
            field=models.CharField(choices=[('sent', 'sent'), ('delivered', 'delivered'), ('read', 'read')], default='sent', max_length=255),
        ),
    ]
