# Generated by Django 5.0.6 on 2024-06-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_attachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='attachment',
            new_name='image',
        ),
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comment_images/'),
        ),
    ]
