# Generated by Django 5.0.6 on 2024-07-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='privacy',
            field=models.CharField(choices=[('public', 'public'), ('friends', 'friends'), ('me', 'me')], default='friends', max_length=255),
        ),
    ]
